title: Crypto Talk
author: Guus van der Stap
email: guusvdstap@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Transcripts of talks from Andreas Antonopoulos on crypto
baseurl: "" # the subpath of your site, e.g. /blog
url: "guusvdstap.github.io"
# twitter_username: onebinaryK
github_username: guusvdstap
timezone: Europe/Amsterdam
show_excerpts: true
excerpt_separator: "<!--more-->"
defaults:
  - scope:
      path: _posts
    values:
      layout: post
# Build settings
theme: minima
# plugins:
#  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
